name: Windows MSVC

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cxx_std: [17, 20, 23]
        os: [windows-2022]
        disable_trace: [false]
        include:
          # Test with trace disabled
          - cxx_std: 20
            os: windows-2022
            disable_trace: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. Visual Studio is a multi-config generator, so we don't use CMAKE_BUILD_TYPE.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          if ("${{ matrix.disable_trace }}" -eq "true") {
            cmake -B build -DCXX_STD=${{ matrix.cxx_std }} -DDISABLE_TRACE=true
          } else {
            cmake -B build -DCXX_STD=${{ matrix.cxx_std }}
          }
        shell: pwsh

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -- /p:CL_MPcount=4

      - name: Test
        working-directory: build/test
        run: ctest -j4 -C ${{ env.BUILD_TYPE }} --output-on-failure
